version: '3.8'
services:
  api:
    container_name: api
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - 3000:3000
    command: yarn dev
    networks:
      - app-network

  db:
    image: postgres:9.6
    container_name: db
    env_file: 
      - .env
    volumes:
      - dbdata-volume:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: GMT
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata-volume: